"""collect_data — code-tier handler for work 'quality_analyst'.

generated by OpenWorkCompiler build emitter (core/build) — edit freely, regenerate with care
executor handler ref: services.collect_data
"""


EXAMPLE_INPUT = {}
EXAMPLE_OUTPUT = {}


def run(**inputs):
    """Deterministic implementation of ``collect_data``.

    TODO: replace the body below with the real logic. The recorded example
    (EXAMPLE_INPUT -> EXAMPLE_OUTPUT) documents the contract this handler must honour.
    Expected input keys: see work.yaml inputs
    """
    raise NotImplementedError("handler 'collect_data' is a scaffold; implement run(**inputs)")
