"""Fine-tune the SLM executor for 'create_report' (work 'quality_analyst') with TRL SFTTrainer.

generated by OpenWorkflow build emitter (core/build) — edit freely, regenerate with care
Usage: python3 train.py   (reads training_candidate.yaml + dataset.jsonl next to this file)
"""

import json
from pathlib import Path

import yaml

HERE = Path(__file__).parent
CANDIDATE = yaml.safe_load((HERE / "training_candidate.yaml").read_text())
ROWS = [json.loads(line) for line in (HERE / "dataset.jsonl").read_text().splitlines() if line.strip()]


def main() -> None:
    if not ROWS:
        raise SystemExit("dataset.jsonl is empty — approve more traces for 'create_report' first")
    try:
        from datasets import Dataset
        from trl import SFTConfig, SFTTrainer
    except ImportError as exc:
        raise SystemExit(f"install transformers, datasets and trl to fine-tune: {exc}")
    hp = CANDIDATE.get("hyperparameters", {})
    dataset = Dataset.from_list(ROWS)
    trainer = SFTTrainer(
        model=CANDIDATE["base_model"],
        train_dataset=dataset,
        args=SFTConfig(output_dir=str(HERE / "checkpoints"),
                       learning_rate=hp.get("learning_rate", 2e-4),
                       num_train_epochs=hp.get("epochs", 3)),
    )
    trainer.train()
    trainer.save_model(str(HERE / "adapter"))


if __name__ == "__main__":
    main()
